# Generated by Django 3.2.13 on 2022-05-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0003_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['date']},
        ),
    ]
